= Malware Detection

== Overview

In this module you will evaluate your system for the potential presence of Malware using the Insights Malware detection service.

Red Hat has partnered with IBM X-Force Threat Intelligence to access their malware signature database.   +
Insights uses YARA to evaluate the system for the presence of malware. +
This requires additional setup above and beyond Insights registration.

=== Setting up Malware Detection

Go to your host’s terminal window.

First install yara +
[source,sh,role=installyara]
----
sudo dnf install yara -y
----


Initiate yara by running the malware detection collector command: +
[source,sh,role=initiatemalware]
----
sudo insights-client --collector malware-detection
----


Since malware had never been run before on this system the malware detection service performed some setup including the creation of a config file.  
You will need to edit the config file to make scans live.  Edit the config file:
[source,sh,role=editconfig]
----
sudo vi /etc/insights-client/malware-detection-config.yml
----


Inside the file you need to locate the section on test scan. +
Change: +
`Test_scan: true` +
To: +
`Test_scan: false`

Save and exit the text editor.

[If you aren’t familiar with vi, go to the end of the line and press `i` to enter editing mode. +
Delete “true” then type in “false” +
Press the `esc` key to exit editing mode. +
Type:
`:wq`  +
To write the file and quit the editor.]

The Malware detection service is now setup. +
Since this is a new system, there is nothing to find.

On your host you should be in your user’s home directory.  +
Run the ls command.  You should not see any files.

We will go ahead and have this system generate a malware detection hit. +
To do this we will use the eicar set of test files.

More information about eicar is available here if you would like to learn more:  https://www.eicar.org/download-anti-malware-testfile/[https://www.eicar.org/download-anti-malware-testfile/] 

This set of test files includes 4 different files that tests the detection of malware in 4 different ways.   +
On your host we will use the curl command to copy the files from the eicar webpage onto your host.

Run the following commands: +
[source,sh,role=addmalware]
----
sudo curl https://secure.eicar.org/eicar.com -o /home/ec2-user/eicar.com +
sudo curl https://secure.eicar.org/eicar.com.txt -o /home/ec2-user/eicar.com.txt +
sudo curl https://secure.eicar.org/eicar_com.zip -o /home/ec2-user/eicar_com.zip +
sudo curl https://secure.eicar.org/eicarcom2.zip -o /home/ec2-user/eicar_com2.zip
----

Run the ls command. +
You should see the 4 eicar files in your directory.

Each file contains the same test which simulates a malware signature: +
`X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*`

Lets run the malware detection scan on your system.  +
Note this may take several minutes to complete.   +
[source,sh,role=findmalware]
----
sudo insights-client --collector malware-detection
----


In the output you should see: +
[source,textinfo]
----
Scanning files in /home ... +
Matched rule XFTI_EICAR_AV_Test in file /home/ec2-user/eicar.com +
Matched rule XFTI_EICAR_AV_Test in file /home/ec2-user/eicar.com.txt +
Matched rule XFTI_EICAR_AV_Test in file /home/ec2-user/eicar_com.zip +
Matched rule XFTI_EICAR_AV_Test in file /home/ec2-user/eicar_com2.zip
----

That is yara finding the malware signature from eicar in each of the four files.

=== Reviewing Malware Detection Results

Return to the Hybrid Cloud Console. +
On the left hand navigation bar go to `Security → Malware → Signatures`

Here you should see a big red exclamation mark tell you that we have matched a malware signature. +
If there were no malware matches you would see a green checkmark.  Due to the shared environment with multiple people taking this lab it is unlikely you will see the green checkmark today.

Looking next to the exclamation mark you will see the number of matched signatured as well as the number of enabled and disabled signatures.

Malware detection signatures can be disabled in the event that a false positive is detected, but your user account in this lab does not have the permissions to enable or disable signatures.  

Scroll down the page and you will see the matched signature - `XFTI_EICAR_AV_Test`

Click on `XFTI_EICAR_AV_Test`.  You will see the details of the signature and which systems have matched this malware.

Locate your system.  You should notice that you have the date of the last match and the total number of matches.  The total number of matches should be `4` assuming that you only ran the commands as described in the exercise - that is because the eicar package included 4 test files - one match for each of the files.

Click the arrow to the right of your system’s name to expand the details. +
Here you can see the details of the match.  You can download this as a text file or copy it to your clipboard for the purposes of sending these details to the security team.  

If you look through the output you should see 4 different “Match Source” entries - one for each of the eicar files that you put onto the system.  

The Malware detection service does not include any remediation.  This is because each business likely has their own policies and procedures on how malware on systems should be handled once detected.

This module is complete.
