= Registration and Initial use

=== Overview

In this lab we have already provided for you a Red Hat Enterprise Linux (RHEL) 8 host. +
Your RHEL host will be the primary focus of this lab, and you will be using a user account that has access to all of the services of Insights, however to provide the best experience for all users there are some actions you will not be able to do in the lab 


Insights uses the insights-client on each RHEL host to report system facts to Insights for analysis.  +
The insights-client is typically part of the base RHEL image, but you will need to register the host to Insights through a registration command. +
We will start by connecting this host to Insights.

=== Connecting to Insights

There are a couple of different ways to connect to Insights.  In this lab we will use a manual command, but you can also register from a Red Hat Satellite Server if your host is connected to a Satellite or you can leverage an ansible playbook.  If you connect your cloud provider to the Hybrid Cloud Console (console.redhat.com) then systems in the cloud can be automatically registered to Red Hat and Insights.

We will use the rhc command (remote host configuration) which wraps the subscription-manager and the insights registration command into a single command while also enabling some other capabilities like Insights remediation.

We will use an activation key that already exists as well as the organization ID. 

Connect to host via SSH

Run the command:

[source,sh,role=execute]
----
sudo rhc connect -o 13959588 -a AK_Summit_Lab
----

In the output you should see something similar to:


[source,textinfo]
----
[user@myhost ~]$ sudo rhc connect -o 13959588 -a AK_Summit_Lab  +
Connecting myhost.example.com to Red Hat. +
This might take a few seconds. +
● Connected to Red Hat Subscription Management +
● Connected to Red Hat Insights +
● Activated the Remote Host Configuration daemon +
● Enabled console.redhat.com services: remote configuration, insights, compliance, remediations +
Successfully connected to Red Hat! +
Manage your connected systems: https://red.ht/connector +
[user@myhost ~]$ 
----



Your host is now connected to Red Hat and Insights.

This system should now be visible in Insights. +
Open up the Hybrid Cloud Console.


=== Accessing Insights

Log into the Hybrid Cloud Console with the following credentials: 


User:
[source,sh,role=execute]
----
lab-434C
----

Password:
[source,sh,role=execute]
----
R3dh4t2021!
----


This is the main page of the Hybrid Cloud Console.   
There are several offerings available on the Hybrid Cloud Console including Red Hat Insights which is included with subscriptions for Red Hat Enterprise Linux, Red Hat OpenShift, and Red Hat Ansible Automation Platform.

At this point you want to see the system that you just connected to Insights. +
In order to do this, you need to go to the RHEL inventory.  

In the search bar at the top of the page, type: Inventory

There will be several matches.  Select: Inventory | Red Hat Insights 

You will be redirected to the Systems view of the Inventory.   +
This view shows you all of the RHEL hosts that the Hybrid Cloud Console knows about - not all of these systems are necessarily reporting to Insights.  

In addition to Insights, subscription-manager (subman) and Red Hat Satellite also report systems to this inventory to give you a more complete view of your total RHEL estate.

In the list of systems locate your host. +
Reminder: your system name is: {bastion_hostname}

It should be near the top of the page since it was recently connected, but you can also use the “Filter by name” to easily find your system.  Click on the system name to view details about your system.

The inventory view of your specific system will give you an idea of the type of information that Insights uses for its analysis.  

Based on the information that is collected, Insights has analyzed the system and within the inventory view you can see select findings on the Advisor, Vulnerability, Compliance, Patch, and Resource Optimization tabs.   Not all of these tabs will initially have data - this is expected as some services like Compliance and Resource Optimization require additional configuration.  +
We will spend more time on some of these in subsequent exercises.

NOTE: We will not cover every service in Insights during this lab as there is a lot to cover and limited time.  If you have any questions about specific services, please ask your lab facilitators.

=== Data Collection and Security information

Let’s end this activity with a brief discussion on data collection and security information +
It should be reiterated that you have complete control over what information Insights for RHEL gathers - while we have exposed the hostname and IP addresses of the systems in the lab, this information is easily obfuscated via a switch in the client.   Additional information can also be obfuscated including keywords, patterns, and specific files.

Information about data collection can be found on the https://www.redhat.com/en/technologies/management/insights/data-application-security[Red Hat Insights data and application security page].

This page also will tell you how to do things like obfuscate data or perform a collection for inspection to see everything that Insights collects.

It is also important to mention that in our lab we directly connected a system to Insights.  Port 443 is all that needed to be open.   A web proxy is supported.
If you use Satellite, the connection is automatically proxied through capsules (if used) to the Satellite, then onto Insights.

Additional information can be found in the http://redhat.com/insightsfaq[frequently asked questions document].

This module is complete.
